"""Execute named SQL analyses and export reproducible result files."""

from __future__ import annotations

import json
import re
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from time import perf_counter

import pandas as pd

from aquatic_wildlife.config import (
    ANALYSIS_RESULTS_DIR,
    ANALYSIS_SQL_PATH,
    DATABASE_PATH,
)


QUERY_PATTERN = re.compile(
    r"^--\s*name:\s*([A-Za-z0-9_]+)\s*$"
    r"(.*?)"
    r"(?=^--\s*name:|\Z)",
    flags=re.MULTILINE | re.DOTALL,
)


def parse_named_queries(sql_path: Path = ANALYSIS_SQL_PATH) -> dict[str, str]:
    """Parse query blocks introduced by a ``-- name:`` marker."""

    if not sql_path.exists():
        raise FileNotFoundError(f"SQL catalogue was not found: {sql_path}")

    sql_text = sql_path.read_text(encoding="utf-8")
    queries: dict[str, str] = {}

    for match in QUERY_PATTERN.finditer(sql_text):
        name = match.group(1)
        query = match.group(2).strip()

        if query.endswith(";"):
            query = query[:-1].rstrip()

        if not query:
            raise ValueError(f"Named query contains no SQL: {name}")
        if name in queries:
            raise ValueError(f"Duplicate query name: {name}")

        queries[name] = query

    if not queries:
        raise ValueError(
            f"No named queries were found in SQL catalogue: {sql_path}"
        )

    return queries


def run_sql_analyses(
    database_path: Path = DATABASE_PATH,
    sql_path: Path = ANALYSIS_SQL_PATH,
    output_dir: Path = ANALYSIS_RESULTS_DIR,
) -> pd.DataFrame:
    """Execute every named query and export one CSV per result."""

    if not database_path.exists():
        raise FileNotFoundError(
            f"SQLite database was not found: {database_path}. "
            "Run scripts/build_database.py first."
        )

    queries = parse_named_queries(sql_path)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Remove only CSV files generated by this catalogue on earlier runs.
    for name in queries:
        (output_dir / f"{name}.csv").unlink(missing_ok=True)

    manifest_rows: list[dict[str, object]] = []

    with sqlite3.connect(database_path) as connection:
        for position, (name, query) in enumerate(queries.items(), start=1):
            started = perf_counter()
            result = pd.read_sql_query(query, connection)
            duration = perf_counter() - started

            output_path = output_dir / f"{name}.csv"
            result.to_csv(output_path, index=False)

            manifest_rows.append(
                {
                    "position": position,
                    "query_name": name,
                    "row_count": int(len(result)),
                    "column_count": int(result.shape[1]),
                    "duration_seconds": round(duration, 6),
                    "output_file": output_path.name,
                    "status": "succeeded",
                }
            )

    manifest = pd.DataFrame(manifest_rows)
    manifest.to_csv(output_dir / "analysis_manifest.csv", index=False)

    summary = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "database": database_path.name,
        "sql_catalogue": sql_path.name,
        "query_count": len(queries),
        "successful_query_count": int(
            manifest["status"].eq("succeeded").sum()
        ),
        "total_exported_rows": int(manifest["row_count"].sum()),
        "synthetic_data_caveat": (
            "Exports summarize patterns in the supplied educational dataset. "
            "They are not population estimates or independent ecological "
            "evidence."
        ),
    }
    (output_dir / "analysis_summary.json").write_text(
        json.dumps(summary, indent=2),
        encoding="utf-8",
    )

    return manifest
